[assembly:XmlnsDefinition("Wu.CommTool.Core", "Wu.CommTool.Core")]
[assembly:XmlnsDefinition("Wu.CommTool.Core", "Wu.CommTool.Core.Enums")]
[assembly:XmlnsDefinition("Wu.CommTool.Core", "Wu.CommTool.Core.Enums.Modbus")]
[assembly:XmlnsDefinition("Wu.CommTool.Core", "Wu.CommTool.Core.Enums.Mqtt")]
[assembly:XmlnsDefinition("Wu.CommTool.Core", "Wu.CommTool.Core.Models")]
[assembly:XmlnsPrefix("Wu.CommTool.Core", "core")]